hello:
	curl http://localhost:1323/

test:
	curl http://localhost:1323/test

f:
	curl http://localhost:1323/get_friend_list?ID=1
# curl http://localhost:1323/get_friend_list?ID=$(ID)

up:
	docker-compose up -d

down:
	docker-compose down

re : down up